export class ROUTES {
  static readonly INDEX: string = 'pages/Index';
  static readonly STATISTICS: string = 'pages/Statistics';
  static readonly ASSETS: string = 'pages/Assets';
  static readonly PROFILE: string = 'pages/Profile';
  static readonly RECORD_EDIT: string = 'pages/RecordEdit';
  static readonly RECORD_DETAIL: string = 'pages/RecordDetail';
  static readonly CATEGORY_PICKER: string = 'pages/CategoryPicker';
  static readonly ACCOUNT_PICKER: string = 'pages/AccountPicker';
  static readonly CATEGORY_MANAGE: string = 'pages/CategoryManage';
  static readonly ACCOUNT_MANAGE: string = 'pages/AccountManage';
  static readonly BUDGET_SETTING: string = 'pages/BudgetSetting';
  static readonly SEARCH: string = 'pages/Search';
  static readonly CALENDAR: string = 'pages/Calendar';
  static readonly DATA_EXPORT: string = 'pages/DataExport';
  static readonly ALIPAY_IMPORT: string = 'pages/AlipayImport';
  static readonly AUTO_BOOKKEEPING: string = 'pages/AutoBookkeeping';
  static readonly SETTINGS: string = 'pages/Settings';
  static readonly ABOUT: string = 'pages/About';
}
